## Import libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
L = 30
D = 5
P1 = 0.5
P2 = 16

In [3]:
C = np.random.random(size=(L, D)) * 10
print(C.shape)

(30, 5)


In [4]:
A = np.arange(D).reshape([D, 1])
print(A)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [5]:
B = np.arange(D).reshape([1, D])
print(B)

[[0 1 2 3 4]]


In [6]:
S = np.abs(A-B).astype(np.float32)
print(S)

[[0. 1. 2. 3. 4.]
 [1. 0. 1. 2. 3.]
 [2. 1. 0. 1. 2.]
 [3. 2. 1. 0. 1.]
 [4. 3. 2. 1. 0.]]


In [7]:
mask_p1 = S==1
print(mask_p1.astype(int))

[[0 1 0 0 0]
 [1 0 1 0 0]
 [0 1 0 1 0]
 [0 0 1 0 1]
 [0 0 0 1 0]]


In [8]:
mask_p2 = S>1
print(mask_p2.astype(int))

[[0 0 1 1 1]
 [0 0 0 1 1]
 [1 0 0 0 1]
 [1 1 0 0 0]
 [1 1 1 0 0]]


In [9]:
S[mask_p1] = P1 # P1 = 0.5
S[mask_p2] = P2 # P2 = 16
S

array([[ 0. ,  0.5, 16. , 16. , 16. ],
       [ 0.5,  0. ,  0.5, 16. , 16. ],
       [16. ,  0.5,  0. ,  0.5, 16. ],
       [16. , 16. ,  0.5,  0. ,  0.5],
       [16. , 16. , 16. ,  0.5,  0. ]], dtype=float32)

In [10]:
C.shape, S.shape

((30, 5), (5, 5))

In [11]:
C[:,np.newaxis,:].shape, S[np.newaxis,:,:].shape

((30, 1, 5), (1, 5, 5))

In [12]:
C_add_S = C[:,np.newaxis,:] + S[np.newaxis,:,:]

# alternatively
# C_add_S = C.reshape(C.shape[0], 1, C.shape[1]) + S.reshape(1, S.shape[0], S.shape[1])

C_add_S.shape

(30, 5, 5)

In [13]:
out = np.min(C_add_S, axis=1)
out.shape

(30, 5)